#!/usr/bin/env python3
"""High-throughput multi-GPU GigaPath-Flash tile feature extraction.

Architecture
------------
- One long-lived process per GPU. Each process loads exactly one tile encoder.
- A GPU worker owns exactly one WSI at a time until that WSI is finished.
- For the active WSI, one CPU producer thread manages a ThreadPoolExecutor.
  Each parser thread owns its own OpenSlide handle and decodes patches in parallel.
- CPU -> GPU handoff uses a bounded in-process queue of pinned uint8 batches.
  When the queue is full the producer blocks (backpressure); no unbounded cache.
- A dedicated CUDA copy stream prefetches the next uint8 batch while the current
  batch is being inferred.
- WSI tasks are dynamically claimed by the four GPU workers, largest slides first,
  which reduces the long tail without ever splitting one WSI across GPUs.

Expected coordinate CSV columns (generated by generate_gigapath_coords.py):
    case_id,x_l0,y_l0,x_20x,y_20x,tissue_ratio

For OWL/LEOPARD, each selected patch is read as 512x512 from 40x level-0,
resized to 256x256 (20x), then center-cropped to 224x224 exactly as in the
official GigaPath-Flash tile-encoder preprocessing.
"""

from __future__ import annotations

import os
os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("NUMEXPR_NUM_THREADS", "1")

import argparse
import csv
import queue
import sys
import threading
import time
import traceback
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Optional

import numpy as np
import torch
from PIL import Image


MODEL_REPO = "prov-gigapath/prov-gigapath-flash"
FEATURE_DIM = 384
IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)

LEVEL0_READ_SIZE = 512
RESIZE_SIZE = 256
MODEL_INPUT_SIZE = 224
CROP_OFFSET = (RESIZE_SIZE - MODEL_INPUT_SIZE) // 2

_END = object()
_READER_TLS = threading.local()
_READER_REGISTRY: list[Any] = []
_READER_REGISTRY_LOCK = threading.Lock()


@dataclass(frozen=True)
class WSITask:
    case_id: str
    slide_path: str
    coord_path: str
    output_path: str
    num_tiles: int


@dataclass(frozen=True)
class WorkerConfig:
    parser_threads: int
    batch_size: int
    queue_batches: int
    amp_dtype: str
    feature_dtype: str
    compile_model: bool


@dataclass
class BatchPayload:
    images: torch.Tensor
    start: int
    end: int


@dataclass
class ProducerFailure:
    message: str
    trace: str


@dataclass
class StagedBatch:
    payload: BatchPayload
    images_gpu: torch.Tensor
    ready_event: torch.cuda.Event


def parse_gpu_ids(text: str) -> list[int]:
    gpu_ids = [int(x.strip()) for x in text.split(",") if x.strip()]
    if not gpu_ids:
        raise ValueError("--gpus must contain at least one GPU id")
    if len(set(gpu_ids)) != len(gpu_ids):
        raise ValueError(f"Duplicate GPU ids in --gpus: {gpu_ids}")
    return gpu_ids


def load_summary_counts(coords_dir: Path) -> dict[str, int]:
    summary_path = coords_dir / "summary.csv"
    if not summary_path.is_file():
        return {}
    counts: dict[str, int] = {}
    with summary_path.open("r", newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            try:
                counts[row["case_id"]] = int(row["num_tiles"])
            except (KeyError, TypeError, ValueError):
                continue
    return counts


def count_coord_rows(path: Path) -> int:
    with path.open("rb") as f:
        n_lines = sum(1 for _ in f)
    return max(0, n_lines - 1)


def discover_tasks(
    data_dir: Path,
    coords_dir: Path,
    output_dir: Path,
    overwrite: bool,
    max_cases: Optional[int],
) -> tuple[list[WSITask], int, int]:
    summary_counts = load_summary_counts(coords_dir)
    tasks: list[WSITask] = []
    missing_wsi = 0
    existing_output = 0

    for coord_path in sorted(coords_dir.glob("*.csv")):
        if coord_path.name == "summary.csv":
            continue
        case_id = coord_path.stem
        slide_path = data_dir / f"{case_id}.tif"
        output_path = output_dir / f"{case_id}.pt"
        if not slide_path.is_file():
            missing_wsi += 1
            continue
        if output_path.is_file() and not overwrite:
            existing_output += 1
            continue
        num_tiles = summary_counts.get(case_id)
        if num_tiles is None:
            num_tiles = count_coord_rows(coord_path)
        tasks.append(
            WSITask(
                case_id=case_id,
                slide_path=str(slide_path),
                coord_path=str(coord_path),
                output_path=str(output_path),
                num_tiles=num_tiles,
            )
        )

    tasks.sort(key=lambda t: t.num_tiles, reverse=True)
    if max_cases is not None:
        tasks = tasks[:max_cases]
    return tasks, missing_wsi, existing_output


def load_coords(coord_path: Path) -> tuple[np.ndarray, np.ndarray]:
    """Return (coords_l0, coords_20x), each int64 [N, 2]."""
    with coord_path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        try:
            header = next(reader)
        except StopIteration:
            raise ValueError(f"Empty coordinate CSV: {coord_path}")
        col = {name: i for i, name in enumerate(header)}
        required = ("x_l0", "y_l0", "x_20x", "y_20x")
        missing = [name for name in required if name not in col]
        if missing:
            raise ValueError(f"Missing columns {missing} in {coord_path}")
        rows = [
            (
                int(row[col["x_l0"]]),
                int(row[col["y_l0"]]),
                int(row[col["x_20x"]]),
                int(row[col["y_20x"]]),
            )
            for row in reader
            if row
        ]
    if not rows:
        empty = np.empty((0, 2), dtype=np.int64)
        return empty, empty.copy()
    arr = np.asarray(rows, dtype=np.int64)
    return arr[:, :2], arr[:, 2:4]


def _init_slide_reader(slide_path: str) -> None:
    try:
        import openslide
    except ImportError as exc:
        raise RuntimeError(
            "openslide-python is required. Install the Python package and the "
            "system OpenSlide library before running feature extraction."
        ) from exc
    reader = openslide.OpenSlide(slide_path)
    _READER_TLS.reader = reader
    with _READER_REGISTRY_LOCK:
        _READER_REGISTRY.append(reader)


def _close_registered_readers() -> None:
    global _READER_REGISTRY
    with _READER_REGISTRY_LOCK:
        readers = _READER_REGISTRY
        _READER_REGISTRY = []
    for reader in readers:
        try:
            reader.close()
        except Exception:
            pass


def _read_patch_into(dest: torch.Tensor, x_l0: int, y_l0: int) -> None:
    """Decode one WSI patch and write CHW uint8 directly into pinned memory."""
    reader = getattr(_READER_TLS, "reader", None)
    if reader is None:
        raise RuntimeError("OpenSlide reader was not initialized in parser thread")

    rgba = reader.read_region(
        (int(x_l0), int(y_l0)),
        0,
        (LEVEL0_READ_SIZE, LEVEL0_READ_SIZE),
    )
    if rgba.mode == "RGBA":
        rgb = Image.new("RGB", rgba.size, (255, 255, 255))
        rgb.paste(rgba, mask=rgba.getchannel("A"))
    else:
        rgb = rgba.convert("RGB")

    rgb = rgb.resize((RESIZE_SIZE, RESIZE_SIZE), resample=Image.Resampling.BICUBIC)
    rgb = rgb.crop(
        (
            CROP_OFFSET,
            CROP_OFFSET,
            CROP_OFFSET + MODEL_INPUT_SIZE,
            CROP_OFFSET + MODEL_INPUT_SIZE,
        )
    )
    arr = np.array(rgb, dtype=np.uint8, copy=True)
    chw = np.ascontiguousarray(arr.transpose(2, 0, 1))
    dest.copy_(torch.from_numpy(chw))


def _put_with_backpressure(
    out_q: queue.Queue,
    item: Any,
    stop_event: threading.Event,
    stats: dict[str, float],
) -> bool:
    wait_start = time.perf_counter()
    while not stop_event.is_set():
        try:
            out_q.put(item, timeout=0.25)
            stats["blocked_s"] += time.perf_counter() - wait_start
            return True
        except queue.Full:
            continue
    stats["blocked_s"] += time.perf_counter() - wait_start
    return False


def _produce_batches(
    slide_path: str,
    coords_l0: np.ndarray,
    batch_size: int,
    parser_threads: int,
    out_q: queue.Queue,
    stop_event: threading.Event,
    stats: dict[str, float],
) -> None:
    try:
        _close_registered_readers()
        with ThreadPoolExecutor(
            max_workers=parser_threads,
            thread_name_prefix="patch-reader",
            initializer=_init_slide_reader,
            initargs=(slide_path,),
        ) as pool:
            n = len(coords_l0)
            for start in range(0, n, batch_size):
                if stop_event.is_set():
                    break
                end = min(start + batch_size, n)
                size = end - start
                t0 = time.perf_counter()
                images = torch.empty(
                    (size, 3, MODEL_INPUT_SIZE, MODEL_INPUT_SIZE),
                    dtype=torch.uint8,
                    pin_memory=True,
                )
                futures = [
                    pool.submit(
                        _read_patch_into,
                        images[i],
                        int(coords_l0[start + i, 0]),
                        int(coords_l0[start + i, 1]),
                    )
                    for i in range(size)
                ]
                for future in futures:
                    future.result()
                stats["decode_s"] += time.perf_counter() - t0
                stats["tiles"] += float(size)
                if not _put_with_backpressure(
                    out_q,
                    BatchPayload(images=images, start=start, end=end),
                    stop_event,
                    stats,
                ):
                    return

        if not stop_event.is_set():
            _put_with_backpressure(out_q, _END, stop_event, stats)
    except Exception as exc:
        if not stop_event.is_set():
            failure = ProducerFailure(message=str(exc), trace=traceback.format_exc())
            _put_with_backpressure(out_q, failure, stop_event, stats)
    finally:
        _close_registered_readers()


def _get_queue_item(batch_q: queue.Queue, blocking: bool) -> tuple[Any, float]:
    t0 = time.perf_counter()
    if blocking:
        item = batch_q.get()
    else:
        item = batch_q.get_nowait()
    return item, time.perf_counter() - t0


def _stage_batch(
    payload: BatchPayload,
    device: torch.device,
    copy_stream: torch.cuda.Stream,
) -> StagedBatch:
    with torch.cuda.stream(copy_stream):
        images_gpu = payload.images.to(device=device, non_blocking=True)
        ready = torch.cuda.Event(blocking=False)
        ready.record(copy_stream)
    return StagedBatch(payload=payload, images_gpu=images_gpu, ready_event=ready)


def _handle_special_queue_item(item: Any) -> Optional[bool]:
    if item is _END:
        return True
    if isinstance(item, ProducerFailure):
        raise RuntimeError(f"CPU producer failed: {item.message}\n{item.trace}")
    return None


def _storage_dtype(name: str) -> torch.dtype:
    if name == "float16":
        return torch.float16
    if name == "float32":
        return torch.float32
    raise ValueError(name)


def _amp_dtype(name: str) -> torch.dtype:
    if name == "bf16":
        return torch.bfloat16
    if name == "fp16":
        return torch.float16
    raise ValueError(name)


def save_feature_file(
    task: WSITask,
    features: torch.Tensor,
    coords_20x: np.ndarray,
    coords_l0: np.ndarray,
    feature_dtype: str,
) -> None:
    output_path = Path(task.output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = output_path.with_suffix(output_path.suffix + ".tmp")
    payload = {
        "case_id": task.case_id,
        "model": MODEL_REPO,
        "features": features.to(dtype=_storage_dtype(feature_dtype)).contiguous(),
        "coords": torch.from_numpy(coords_20x.astype(np.int32, copy=False)).contiguous(),
        "coords_l0": torch.from_numpy(coords_l0.astype(np.int32, copy=False)).contiguous(),
        "tile_size_20x": RESIZE_SIZE,
        "model_input_size": MODEL_INPUT_SIZE,
        "level0_read_size": LEVEL0_READ_SIZE,
    }
    torch.save(payload, tmp_path)
    os.replace(tmp_path, output_path)


def run_one_wsi(
    task: WSITask,
    model: torch.nn.Module,
    device: torch.device,
    cfg: WorkerConfig,
) -> dict[str, float]:
    coords_l0, coords_20x = load_coords(Path(task.coord_path))
    n_tiles = len(coords_l0)
    if task.num_tiles != n_tiles:
        print(
            f"[WARN] {task.case_id}: summary says {task.num_tiles} tiles, "
            f"coordinate CSV has {n_tiles}",
            flush=True,
        )

    if n_tiles == 0:
        empty_features = torch.empty((0, FEATURE_DIM), dtype=_storage_dtype(cfg.feature_dtype))
        save_feature_file(task, empty_features, coords_20x, coords_l0, cfg.feature_dtype)
        return {
            "tiles": 0.0,
            "wall_s": 0.0,
            "tile_per_s": 0.0,
            "gpu_wait_s": 0.0,
            "producer_blocked_s": 0.0,
            "producer_decode_s": 0.0,
            "gpu_step_s": 0.0,
        }

    batch_q: queue.Queue = queue.Queue(maxsize=cfg.queue_batches)
    stop_event = threading.Event()
    producer_stats = {"blocked_s": 0.0, "decode_s": 0.0, "tiles": 0.0}
    producer = threading.Thread(
        target=_produce_batches,
        args=(
            task.slide_path,
            coords_l0,
            cfg.batch_size,
            cfg.parser_threads,
            batch_q,
            stop_event,
            producer_stats,
        ),
        name=f"producer-{task.case_id}",
        daemon=True,
    )

    copy_stream = torch.cuda.Stream(device=device)
    current_stream = torch.cuda.current_stream(device=device)
    mean = torch.tensor(IMAGENET_MEAN, dtype=torch.float32, device=device).view(1, 3, 1, 1)
    std = torch.tensor(IMAGENET_STD, dtype=torch.float32, device=device).view(1, 3, 1, 1)
    amp_dtype = _amp_dtype(cfg.amp_dtype)
    storage_dtype = _storage_dtype(cfg.feature_dtype)

    features_cpu: list[torch.Tensor] = []
    gpu_wait_s = 0.0
    gpu_step_s = 0.0
    wall_start = time.perf_counter()
    producer.start()

    try:
        first_item, waited = _get_queue_item(batch_q, blocking=True)
        gpu_wait_s += waited
        if _handle_special_queue_item(first_item):
            raise RuntimeError(f"Producer ended before yielding patches for {task.case_id}")
        if not isinstance(first_item, BatchPayload):
            raise TypeError(f"Unexpected queue item: {type(first_item)}")

        current = _stage_batch(first_item, device, copy_stream)
        no_more_batches = False
        expected_start = 0

        while current is not None:
            current_stream.wait_event(current.ready_event)
            if current.payload.start != expected_start:
                raise RuntimeError(
                    f"Batch order error for {task.case_id}: expected start {expected_start}, "
                    f"got {current.payload.start}"
                )
            expected_start = current.payload.end

            next_staged: Optional[StagedBatch] = None
            if not no_more_batches:
                try:
                    next_item, _ = _get_queue_item(batch_q, blocking=False)
                    special = _handle_special_queue_item(next_item)
                    if special:
                        no_more_batches = True
                    else:
                        if not isinstance(next_item, BatchPayload):
                            raise TypeError(f"Unexpected queue item: {type(next_item)}")
                        next_staged = _stage_batch(next_item, device, copy_stream)
                except queue.Empty:
                    pass

            step_start = time.perf_counter()
            x = current.images_gpu.to(dtype=torch.float32)
            x.mul_(1.0 / 255.0)
            x.sub_(mean).div_(std)

            with torch.inference_mode(), torch.autocast(
                device_type="cuda",
                dtype=amp_dtype,
                enabled=True,
            ):
                output = model(x)

            if isinstance(output, (tuple, list)):
                output = output[0]
            if output.ndim != 2 or output.shape[1] != FEATURE_DIM:
                raise RuntimeError(
                    f"Unexpected model output shape {tuple(output.shape)} for {task.case_id}; "
                    f"expected [B, {FEATURE_DIM}]"
                )

            features_cpu.append(output.detach().to(device="cpu", dtype=storage_dtype))
            gpu_step_s += time.perf_counter() - step_start
            del x, output, current

            if next_staged is not None:
                current = next_staged
                continue
            if no_more_batches:
                current = None
                continue

            next_item, waited = _get_queue_item(batch_q, blocking=True)
            gpu_wait_s += waited
            special = _handle_special_queue_item(next_item)
            if special:
                current = None
                no_more_batches = True
            else:
                if not isinstance(next_item, BatchPayload):
                    raise TypeError(f"Unexpected queue item: {type(next_item)}")
                current = _stage_batch(next_item, device, copy_stream)

        producer.join()
        if expected_start != n_tiles:
            raise RuntimeError(
                f"Feature count mismatch for {task.case_id}: consumed {expected_start}, "
                f"expected {n_tiles}"
            )

        features = torch.cat(features_cpu, dim=0)
        if len(features) != n_tiles:
            raise RuntimeError(
                f"Feature tensor mismatch for {task.case_id}: {len(features)} vs {n_tiles}"
            )

        save_feature_file(task, features, coords_20x, coords_l0, cfg.feature_dtype)
        wall_s = time.perf_counter() - wall_start
        return {
            "tiles": float(n_tiles),
            "wall_s": wall_s,
            "tile_per_s": n_tiles / wall_s if wall_s > 0 else 0.0,
            "gpu_wait_s": gpu_wait_s,
            "producer_blocked_s": producer_stats["blocked_s"],
            "producer_decode_s": producer_stats["decode_s"],
            "gpu_step_s": gpu_step_s,
        }

    except Exception:
        stop_event.set()
        producer.join(timeout=10.0)
        raise
    finally:
        stop_event.set()


def load_tile_encoder(checkpoint_path: str, device: torch.device, compile_model: bool) -> torch.nn.Module:
    try:
        import gigapath.tile_encoder as tile_encoder
    except ImportError as exc:
        raise RuntimeError(
            "The Prov-GigaPath package is required. Install the current official "
            "repository (pip install -e /path/to/prov-gigapath) so the "
            "gigapath_tile_enc_dinov2s architecture is registered."
        ) from exc

    model = tile_encoder.create_model(checkpoint_path)
    model.eval().to(device)
    if compile_model:
        model = torch.compile(model, mode="reduce-overhead")
    return model


def gpu_worker(
    gpu_id: int,
    task_q: Any,
    result_q: Any,
    checkpoint_path: str,
    cfg: WorkerConfig,
) -> None:
    try:
        torch.set_num_threads(1)
        torch.set_num_interop_threads(1)
        torch.cuda.set_device(gpu_id)
        device = torch.device(f"cuda:{gpu_id}")
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True
        torch.backends.cudnn.benchmark = True

        model = load_tile_encoder(checkpoint_path, device, cfg.compile_model)
        result_q.put({"type": "worker_ready", "gpu": gpu_id})

        while True:
            task = task_q.get()
            if task is None:
                break
            if not isinstance(task, WSITask):
                raise TypeError(f"Unexpected task type: {type(task)}")

            try:
                stats = run_one_wsi(task, model, device, cfg)
                result_q.put(
                    {
                        "type": "done",
                        "gpu": gpu_id,
                        "case_id": task.case_id,
                        **stats,
                    }
                )
            except Exception as exc:
                tmp_path = Path(task.output_path).with_suffix(Path(task.output_path).suffix + ".tmp")
                try:
                    tmp_path.unlink(missing_ok=True)
                except Exception:
                    pass
                result_q.put(
                    {
                        "type": "task_error",
                        "gpu": gpu_id,
                        "case_id": task.case_id,
                        "error": str(exc),
                        "trace": traceback.format_exc(),
                    }
                )
                torch.cuda.empty_cache()

        result_q.put({"type": "worker_done", "gpu": gpu_id})

    except Exception as exc:
        result_q.put(
            {
                "type": "worker_error",
                "gpu": gpu_id,
                "error": str(exc),
                "trace": traceback.format_exc(),
            }
        )


def resolve_checkpoint(checkpoint: Path) -> Path:
    checkpoint = checkpoint.expanduser().resolve()
    if not checkpoint.is_file():
        raise FileNotFoundError(f"Local GigaPath-Flash checkpoint not found: {checkpoint}")
    return checkpoint


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, required=True, help="Directory containing case_xxx.tif WSIs")
    parser.add_argument("--coords-dir", type=Path, required=True, help="Directory containing per-case coordinate CSVs")
    parser.add_argument("--output-dir", type=Path, required=True, help="Directory for per-case .pt feature files")
    parser.add_argument("--gpus", type=str, default="4,5,6,7", help="Comma-separated physical GPU ids (default: 4,5,6,7)")
    parser.add_argument("--parser-threads", type=int, default=16, help="CPU patch parser threads per active WSI (default: 16)")
    parser.add_argument("--batch-size", type=int, default=512, help="GPU inference batch size per GPU (default: 512)")
    parser.add_argument("--queue-batches", type=int, default=4, help="Bounded CPU cache depth in batches per GPU (default: 4)")
    parser.add_argument("--amp-dtype", choices=("bf16", "fp16"), default="bf16", help="GPU autocast dtype (default: bf16)")
    parser.add_argument("--feature-dtype", choices=("float16", "float32"), default="float16", help="Stored feature dtype (default: float16)")
    parser.add_argument("--checkpoint", type=Path, required=True, help="Path to the local GigaPath-Flash pytorch_model.bin; network download is never attempted")
    parser.add_argument("--compile", action="store_true", dest="compile_model", help="Use torch.compile on each GPU model")
    parser.add_argument("--overwrite", action="store_true", help="Recompute cases whose output .pt already exists")
    parser.add_argument("--max-cases", type=int, default=None, help="Only process the largest N pending cases (for benchmarking)")
    return parser.parse_args()


def validate_args(args: argparse.Namespace, gpu_ids: Iterable[int]) -> None:
    if not args.data_dir.is_dir():
        raise NotADirectoryError(args.data_dir)
    if not args.coords_dir.is_dir():
        raise NotADirectoryError(args.coords_dir)
    if args.parser_threads < 1:
        raise ValueError("--parser-threads must be >= 1")
    if args.batch_size < 1:
        raise ValueError("--batch-size must be >= 1")
    if args.queue_batches < 1:
        raise ValueError("--queue-batches must be >= 1")
    if args.max_cases is not None and args.max_cases < 1:
        raise ValueError("--max-cases must be >= 1")

    n_cuda = torch.cuda.device_count()
    bad = [gpu for gpu in gpu_ids if gpu < 0 or gpu >= n_cuda]
    if bad:
        raise ValueError(f"Requested GPU ids {bad}, but torch sees cuda:0..{n_cuda - 1}")


def format_done(msg: dict[str, Any]) -> str:
    wall = float(msg["wall_s"])
    gpu_wait = float(msg["gpu_wait_s"])
    producer_block = float(msg["producer_blocked_s"])
    wait_pct = 100.0 * gpu_wait / wall if wall > 0 else 0.0
    block_pct = 100.0 * producer_block / wall if wall > 0 else 0.0
    return (
        f"[GPU {msg['gpu']}] {msg['case_id']}: {int(msg['tiles']):,} tiles | "
        f"{msg['tile_per_s']:.1f} tile/s | {wall:.1f}s | "
        f"GPU-wait={gpu_wait:.2f}s ({wait_pct:.1f}%) | "
        f"producer-blocked={producer_block:.2f}s ({block_pct:.1f}%)"
    )


def main() -> None:
    args = parse_args()
    gpu_ids = parse_gpu_ids(args.gpus)
    validate_args(args, gpu_ids)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    tasks, missing_wsi, existing_output = discover_tasks(
        data_dir=args.data_dir,
        coords_dir=args.coords_dir,
        output_dir=args.output_dir,
        overwrite=args.overwrite,
        max_cases=args.max_cases,
    )

    print("GigaPath-Flash producer/consumer feature extraction", flush=True)
    print(f"  GPUs:                  {gpu_ids}", flush=True)
    print(f"  concurrent WSIs:       {len(gpu_ids)} (one per GPU)", flush=True)
    print(f"  parser threads / WSI:  {args.parser_threads}", flush=True)
    print(f"  total parser threads:  {args.parser_threads * len(gpu_ids)}", flush=True)
    print(f"  batch size / GPU:      {args.batch_size}", flush=True)
    print(f"  queue depth / GPU:     {args.queue_batches} batches (bounded)", flush=True)
    print(f"  pending WSIs:          {len(tasks)}", flush=True)
    print(f"  existing outputs skip: {existing_output}", flush=True)
    print(f"  missing WSI skip:      {missing_wsi}", flush=True)

    if not tasks:
        print("Nothing to process.", flush=True)
        return

    checkpoint = resolve_checkpoint(args.checkpoint)
    print(f"  checkpoint:            {checkpoint}", flush=True)

    cfg = WorkerConfig(
        parser_threads=args.parser_threads,
        batch_size=args.batch_size,
        queue_batches=args.queue_batches,
        amp_dtype=args.amp_dtype,
        feature_dtype=args.feature_dtype,
        compile_model=args.compile_model,
    )

    ctx = torch.multiprocessing.get_context("spawn")
    task_q = ctx.Queue()
    result_q = ctx.Queue()

    workers = [
        ctx.Process(
            target=gpu_worker,
            args=(gpu_id, task_q, result_q, str(checkpoint), cfg),
            name=f"gigapath-gpu-{gpu_id}",
        )
        for gpu_id in gpu_ids
    ]
    for proc in workers:
        proc.start()

    for task in tasks:
        task_q.put(task)
    for _ in workers:
        task_q.put(None)

    total_tasks = len(tasks)
    finished = 0
    failed = 0
    total_tiles = 0
    start = time.perf_counter()
    worker_errors = 0

    while finished < total_tasks:
        try:
            msg = result_q.get(timeout=1.0)
        except queue.Empty:
            if all(not proc.is_alive() for proc in workers):
                break
            continue

        msg_type = msg.get("type")
        if msg_type == "worker_ready":
            print(f"[GPU {msg['gpu']}] model ready", flush=True)
        elif msg_type == "done":
            finished += 1
            total_tiles += int(msg["tiles"])
            print(f"[{finished}/{total_tasks}] {format_done(msg)}", flush=True)
        elif msg_type == "task_error":
            finished += 1
            failed += 1
            print(
                f"[{finished}/{total_tasks}] [GPU {msg['gpu']}] ERROR {msg['case_id']}: "
                f"{msg['error']}",
                file=sys.stderr,
                flush=True,
            )
        elif msg_type == "worker_error":
            worker_errors += 1
            print(
                f"[GPU {msg['gpu']}] WORKER ERROR: {msg['error']}\n{msg['trace']}",
                file=sys.stderr,
                flush=True,
            )

    for proc in workers:
        proc.join()

    elapsed = time.perf_counter() - start
    if finished < total_tasks:
        remaining = total_tasks - finished
        raise RuntimeError(
            f"All GPU workers exited with {remaining} WSI tasks unreported. "
            f"Worker errors: {worker_errors}."
        )

    print("\nFinished", flush=True)
    print(f"  WSIs:       {finished - failed}/{total_tasks} succeeded", flush=True)
    print(f"  tiles:      {total_tiles:,}", flush=True)
    print(f"  wall time:  {elapsed:.1f}s", flush=True)
    if elapsed > 0:
        print(f"  aggregate:  {total_tiles / elapsed:.1f} tile/s", flush=True)

    if failed or worker_errors:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
